CREATE TABLE IF NOT EXISTS player
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar NOT NULL,
    position       varchar NOT NULL,
    handedness     varchar NOT NULL,
    player_type    varchar NOT NULL,
    batter_target  int NOT NULL,
    on_base_target int NOT NULL
);